In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(50,50,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 50, 50, 3)]       0         
                                                                 
 conv2d (Conv2D)             (None, 48, 48, 2)         56        
                                                                 
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[-0.00206834,  0.01851779],
          [-0.1678153 , -0.02993128],
          [-0.33965582,  0.2380768 ]],
 
         [[-0.01164639,  0.32092744],
          [-0.14387754,  0.33653933],
          [ 0.2531438 ,  0.00566331]],
 
         [[ 0.12608963, -0.23718873],
          [ 0.18737161,  0.35152727],
          [ 0.34129888, -0.01668453]]],
 
 
        [[[ 0.18752456,  0.26534623],
          [-0.17600486,  0.34782016],
          [ 0.18851066, -0.04291046]],
 
         [[ 0.24036765,  0.2580464 ],
          [-0.34185013,  0.14275628],
          [-0.33296803, -0.05137441]],
 
         [[ 0.01927659, -0.32029888],
          [ 0.348561  , -0.00182161],
          [ 0.10485414,  0.13186333]]],
 
 
        [[[ 0.01778591,  0.24203098],
          [-0.08058617,  0.23277384],
          [ 0.10492831, -0.01445305]],
 
         [[ 0.34216738, -0.14403553],
          [-0.03068775, -0.31158975],
          [-0.1769303 ,  0

In [5]:
X = np.random.rand(1,50,50,3)
X

array([[[[0.58873189, 0.27309095, 0.38984027],
         [0.94809879, 0.86540592, 0.69003936],
         [0.54955133, 0.99301701, 0.8546596 ],
         ...,
         [0.45899403, 0.82196322, 0.6227302 ],
         [0.7832435 , 0.12899436, 0.31856959],
         [0.86273757, 0.79415364, 0.95452688]],

        [[0.63195903, 0.46612874, 0.74043578],
         [0.48259646, 0.03240281, 0.25364832],
         [0.30016643, 0.40939467, 0.23306582],
         ...,
         [0.54315202, 0.23431229, 0.84392828],
         [0.78496985, 0.53429086, 0.6831874 ],
         [0.27850213, 0.34241629, 0.07587986]],

        [[0.83701747, 0.66550763, 0.8224673 ],
         [0.45255086, 0.81261376, 0.88714864],
         [0.33497784, 0.67049506, 0.25652072],
         ...,
         [0.70980619, 0.12608403, 0.5027216 ],
         [0.82412963, 0.51046264, 0.85921181],
         [0.28354456, 0.52827071, 0.79061703]],

        ...,

        [[0.94364852, 0.32960137, 0.20747592],
         [0.20945571, 0.71762739, 0.66852724]

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 101ms/step


2023-06-19 01:16:08.874137: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[ 1.0116493 ,  1.4056368 ],
         [ 0.337425  ,  0.68530476],
         [ 0.14633428,  0.83417094],
         ...,
         [ 0.5404635 ,  0.9085094 ],
         [ 0.8590881 ,  0.7335876 ],
         [ 0.57960474,  0.74524313]],

        [[ 0.34340805,  1.3149275 ],
         [ 0.5441109 ,  0.7135133 ],
         [ 0.01260439,  0.84356207],
         ...,
         [ 0.53422034,  0.78135484],
         [ 1.1054801 ,  0.8000091 ],
         [ 0.5730401 ,  1.3175906 ]],

        [[ 0.32343942,  1.2499185 ],
         [ 0.23533688,  1.2733262 ],
         [-0.06182823,  0.22002205],
         ...,
         [ 1.1104048 ,  0.7312172 ],
         [ 0.29171008,  0.9835338 ],
         [ 0.467455  ,  1.2727609 ]],

        ...,

        [[ 0.43398923,  0.7645634 ],
         [ 0.9580562 ,  0.30134648],
         [ 0.61336565,  0.72916156],
         ...,
         [ 0.5258925 ,  1.2561712 ],
         [ 0.23272645,  0.5790109 ],
         [ 0.1916122 ,  1.2198219 ]],

        [[ 1.061372  ,  0.8393951 

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": [0,0]
}

In [8]:
out_json = (y*1000000).round().astype(int).flatten().tolist()

In [9]:
import json

In [10]:
with open("conv2d/input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv2d/output.json", "w") as f:
    json.dump(out_json, f)