In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

2023-06-21 02:32:42.173650: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-21 02:32:42.212085: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-21 02:32:42.212732: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-21 02:32:42.777654: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
size = 32

In [3]:
inputs = Input(shape=(size,size,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

2023-06-21 02:32:43.276617: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-21 02:32:43.276956: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [4]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32, 32, 3)]       0         
                                                                 
 conv2d (Conv2D)             (None, 30, 30, 2)         56        
                                                                 
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[ 0.3122536 , -0.35768434],
          [-0.00987762, -0.14765742],
          [ 0.33355755, -0.24231836]],
 
         [[ 0.22601944, -0.0510852 ],
          [ 0.16763812, -0.18366624],
          [-0.23919654, -0.18267508]],
 
         [[-0.15984975, -0.18699491],
          [-0.17630164, -0.31214353],
          [ 0.11839971,  0.08551025]]],
 
 
        [[[ 0.08705449,  0.25231212],
          [ 0.20721722,  0.1117636 ],
          [ 0.33332098, -0.15658306]],
 
         [[-0.12726136, -0.08771327],
          [ 0.1495679 ,  0.20597088],
          [-0.0278579 , -0.07690847]],
 
         [[-0.21101634, -0.18417005],
          [-0.25724152, -0.31060773],
          [-0.01970431,  0.14478147]]],
 
 
        [[[-0.33064678, -0.10183489],
          [-0.3399427 , -0.18658887],
          [ 0.31239426, -0.14342543]],
 
         [[ 0.13050434,  0.17122954],
          [-0.24486107,  0.30148482],
          [-0.20103425,  0

In [6]:
X = np.random.rand(1,size,size,3)
X

array([[[[0.01962207, 0.95882094, 0.35828557],
         [0.66550487, 0.62807707, 0.26594954],
         [0.29709729, 0.13306449, 0.28034113],
         ...,
         [0.35003459, 0.77120529, 0.88505744],
         [0.01326928, 0.26015559, 0.69003832],
         [0.26296812, 0.83550691, 0.32521063]],

        [[0.68003668, 0.81460149, 0.89349122],
         [0.43823585, 0.58223146, 0.98929292],
         [0.03339618, 0.22356739, 0.04286964],
         ...,
         [0.94447588, 0.87940499, 0.56501838],
         [0.32576093, 0.67590778, 0.84532205],
         [0.07016307, 0.56203175, 0.2113005 ]],

        [[0.38897787, 0.50762213, 0.54969499],
         [0.86941137, 0.23886399, 0.9375073 ],
         [0.19606372, 0.18509296, 0.64272332],
         ...,
         [0.790154  , 0.03998056, 0.56565164],
         [0.22689347, 0.60002814, 0.28262559],
         [0.77978828, 0.98026195, 0.20742963]],

        ...,

        [[0.73425998, 0.44065066, 0.93817952],
         [0.08291957, 0.87496097, 0.33579409]

In [7]:
y = model.predict(X)
y

1/1 [==============================] - 0s 55ms/step


array([[[[ 5.53051412e-01, -2.09688857e-01],
         [ 4.66239989e-01, -4.12702918e-01],
         [-3.98638010e-01, -3.40451866e-01],
         ...,
         [-2.32634798e-01, -9.52139020e-01],
         [ 2.83016205e-01, -4.17711884e-02],
         [ 2.87053406e-01, -1.21785685e-01]],

        [[ 3.99587080e-02, -3.53074759e-01],
         [ 8.80663753e-01, -9.06149805e-01],
         [-3.84150445e-01, -3.93398516e-02],
         ...,
         [-1.58908695e-01, -6.92625761e-01],
         [ 4.28100407e-01, -1.13344562e+00],
         [ 1.22749675e-02, -4.07587588e-01]],

        [[-1.53791055e-01, -4.32481170e-01],
         [ 1.15713811e+00, -8.24619710e-01],
         [-2.88120776e-01,  4.78724800e-02],
         ...,
         [ 6.42201975e-02, -3.62379551e-01],
         [ 3.75677764e-01, -5.59972286e-01],
         [-1.61908463e-01, -9.79303241e-01]],

        ...,

        [[ 3.68696421e-01, -8.29068720e-01],
         [-1.44384339e-01,  1.28685832e-01],
         [ 3.97836033e-04,  4.52010799

In [8]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": [0,0]
}

In [9]:
out_json = (y*1000000).round().astype(int).flatten().tolist()

In [10]:
import json

In [11]:
with open("conv2d/input.json", "w") as f:
    json.dump(in_json, f)

In [12]:
with open("conv2d/output.json", "w") as f:
    json.dump(out_json, f)